- name: Check if docker is installed
  command: which docker
  register: docker_check
  failed_when: docker_check.rc != 0
  changed_when: false

- name: Check if docker-compose is installed
  command: which docker-compose
  register: docker_compose_check
  failed_when: docker_compose_check.rc != 0
  changed_when: false
